# Generated by Django 4.1.1 on 2022-10-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='toBraille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
